version: '3.8'

services:
  # Database service
  mariadb:
    image: mariadb:latest
    container_name: library-db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - library_network

  # Development service
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-api-dev
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_URL=http://localhost:3000
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
    - ./src:/app/src
    - ./node_modules:/app/node_modules
    # command: npm run dev
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - library_network

volumes:
  mariadb_data:

networks:
  library_network:
    driver: bridge