version: '3.8'

services:
  # Database service
  mariadb:
    image: mariadb:latest
    container_name: library-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3306:3301"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development service
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_URL=http://localhost:3000
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=library_user
      - DB_PASSWORD=library_password
      - DB_NAME=library_db
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb_data: